version: "3.9"
services:
  mysql:
    image: mysql:8.0.27 #mysql镜像
    container_name: mysql8 # 容器名
    restart: on-failure
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456 #root管理员用户密码
    command: #也可以新建my.cnf配置文件挂载进行全局设置
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --skip-name-resolve
      --max_allowed_packet=128M
      --max_connections=3000
      --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ports: #避免出现端口映射错误，建议采用字符串格式
      - "3306:3306"
    volumes:
      #mysql数据库挂载到host物理机目录
      - ./data:/var/lib/mysql
      #容器的配置目录挂载到host物理机目录
      #- ./conf/my.cnf:/etc/mysql/my.cnf
      #设置容器时区与宿主机保持一致
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    networks:
      - mysql

networks:
  mysql:
    external: true